"""Causal memory for the realized value of ordinary capital displacement.

This family does not fit a whole-universe return or ranking model. It records
actual ordinary full-book replacement opportunities generated by the existing
alpha-decay logic. Only after the next-open-to-next-open Config.rebalance
relative return is fully historical may an event influence a later decision.
The sign of the equal-weighted matured challenger-minus-incumbent mean decides
whether ordinary displacement is allowed. All other lifecycle and execution
authority remains the existing fresh-challenger stack.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, replace
from pathlib import Path

import numpy as np

from techquant.config import Config
from techquant.data import Market, file_hash
from research.offensive_campaign_peak_authority import (
    Owner as ChampionOwner,
    Parameters as ChampionParameters,
)
from research.offensive_fresh_challenger_authority import (
    Owner as FreshOwner,
    Parameters as FreshParameters,
)
from research.quantity_obligation import preserve_trace, verify_trace


@dataclass(frozen=True)
class Parameters:
    enabled: bool

    def __post_init__(self):
        if type(self.enabled) is not bool:
            raise ValueError("enabled must be boolean")


def grid():
    return [Parameters(False), Parameters(True)]


class Owner:
    def __init__(self, market: Market, parameters: Parameters):
        if type(parameters) is not Parameters:
            raise ValueError("matured displacement memory requires registered parameters")
        self.market = market
        self.parameters = parameters
        self.control = ChampionOwner(market, ChampionParameters(True))
        self.parent = FreshOwner(market, FreshParameters(True))
        self.horizon = Config().rebalance
        self.execution_open = market.panel("open").to_numpy(dtype=float)
        self.pending_events: list[dict] = []
        self.matured_sum = 0.0
        self.matured_count = 0
        n = len(market.symbols)
        self.actual_was_held = np.zeros(n, dtype=bool)
        self.campaign_peak_close = np.full(n, np.nan)

    @property
    def trace(self):
        return self.control.trace if not self.parameters.enabled else self.parent.trace

    @property
    def memory_mean(self):
        if self.matured_count == 0:
            return None
        return self.matured_sum / self.matured_count

    def _event(self, observation, action: str, **extra) -> None:
        self.parent.base.trace.append({
            "kind": "MATURED_DISPLACEMENT_MEMORY_EVENT",
            "date": observation.date,
            "session": int(observation.session),
            "action": action,
            **extra,
        })

    def _mature_events(self, current_session: int) -> None:
        for event in self.pending_events:
            if event.get("matured"):
                continue
            start = int(event["origin"]) + 1
            end = start + self.horizon
            if end > current_session:
                continue
            event["matured"] = True
            incumbent = int(event["incumbent"])
            challenger = int(event["challenger"])
            if end >= len(self.execution_open):
                continue
            values = (
                self.execution_open[start, incumbent],
                self.execution_open[end, incumbent],
                self.execution_open[start, challenger],
                self.execution_open[end, challenger],
            )
            if any(not np.isfinite(v) or v <= 0 for v in values):
                event["valid"] = False
                continue
            inc_start, inc_end, chal_start, chal_end = values
            advantage = float(np.log(chal_end / chal_start) - np.log(inc_end / inc_start))
            event["valid"] = True
            event["advantage"] = advantage
            self.matured_sum += advantage
            self.matured_count += 1

    def _observe_campaign_peak(self, observation) -> None:
        held = observation.units > 1e-10
        close = self.parent.base.price_signals.price[observation.session]
        started = held & ~self.actual_was_held
        continuing = held & self.actual_was_held
        self.campaign_peak_close[started] = close[started]
        finite = continuing & np.isfinite(close)
        self.campaign_peak_close[finite] = np.where(
            np.isfinite(self.campaign_peak_close[finite]),
            np.maximum(self.campaign_peak_close[finite], close[finite]),
            close[finite],
        )
        self.campaign_peak_close[~held] = np.nan
        self.actual_was_held = held.copy()

    def _ordinary_pair(self, observation):
        b = self.parent.base
        i = observation.session
        held = observation.units > 1e-10
        if int(held.sum()) != b.config.max_positions or not b.trend.market[i]:
            return None
        p = b.price_signals
        score = b.features.score[i]
        broken = b.trend.exit[i] | (p.ret1[i] <= -0.08) | ~p.ready[i]
        if np.any(held & broken):
            return None
        allowed = (
            p.ready[i]
            & b.trend.entry[i]
            & (p.price[i] > p.ema20[i])
            & (p.momentum5[i] > 0)
            & np.isfinite(score)
            & (score > 0)
            & ~held
            & ~broken
            & ~b.retired
            & ~self.parent.invalidated
        )
        decay = score - b.owned_alpha_reference
        decayed = held & np.isfinite(decay) & (decay < 0)
        challengers = np.flatnonzero(allowed)
        if not np.any(decayed) or not len(challengers):
            return None
        incumbent = min(np.flatnonzero(decayed), key=lambda j: (decay[j], self.market.symbols[j]))
        challenger = min(challengers, key=lambda j: (-score[j], self.market.symbols[j]))
        if not np.isfinite(b.owned_alpha_reference[incumbent]) or score[challenger] <= b.owned_alpha_reference[incumbent]:
            return None
        return incumbent, challenger

    def _call_with_campaign_peak_fallback(self, observation, pair):
        if pair is None:
            return self.parent.decide(observation)
        b = self.parent.base
        i = observation.session
        incumbent, challenger = pair
        fresh_edge = b.trend.entry[i, challenger] and (i == 0 or not b.trend.entry[i - 1, challenger])
        at_peak = (
            np.isfinite(self.campaign_peak_close[incumbent])
            and np.isfinite(b.price_signals.price[i, incumbent])
            and b.price_signals.price[i, incumbent] >= self.campaign_peak_close[incumbent]
        )
        if not (fresh_edge and at_peak):
            return self.parent.decide(observation)
        original = b.features
        masked = original.score.copy()
        masked[i, challenger] = np.nan
        b.features = replace(original, score=masked)
        self._event(
            observation,
            "MEMORY_FALLBACK_CAMPAIGN_PEAK_BLOCK",
            incumbent=self.market.symbols[incumbent],
            challenger=self.market.symbols[challenger],
        )
        try:
            return self.parent.decide(observation)
        finally:
            b.features = original

    def _call_blocking_ordinary_displacement(self, observation, pair):
        if pair is None:
            return self.parent.decide(observation)
        b = self.parent.base
        i = observation.session
        incumbent, challenger = pair
        original_decide = b.decide

        def guarded(current):
            trend = b.trend
            market = trend.market.copy()
            market[i] = False
            b.trend = replace(trend, market=market)
            try:
                return original_decide(current)
            finally:
                b.trend = trend

        b.decide = guarded
        self._event(
            observation,
            "MEMORY_BLOCK_DISPLACEMENT",
            incumbent=self.market.symbols[incumbent],
            challenger=self.market.symbols[challenger],
            memory_mean=float(self.memory_mean),
            matured_count=int(self.matured_count),
        )
        try:
            return self.parent.decide(observation)
        finally:
            b.decide = original_decide

    def decide(self, observation):
        if not self.parameters.enabled:
            return self.control.decide(observation)

        i = observation.session
        self._observe_campaign_peak(observation)
        self._mature_events(i)
        pair = self._ordinary_pair(observation)
        memory = self.memory_mean
        if pair is not None:
            self.pending_events.append({
                "origin": int(i),
                "incumbent": int(pair[0]),
                "challenger": int(pair[1]),
                "matured": False,
            })
            self._event(
                observation,
                "OPPORTUNITY_REGISTERED",
                incumbent=self.market.symbols[pair[0]],
                challenger=self.market.symbols[pair[1]],
                matured_count=int(self.matured_count),
                memory_mean=None if memory is None else float(memory),
            )

        if memory is None:
            return self._call_with_campaign_peak_fallback(observation, pair)
        if memory > 0:
            if pair is not None:
                self._event(
                    observation,
                    "MEMORY_ALLOW_DISPLACEMENT",
                    incumbent=self.market.symbols[pair[0]],
                    challenger=self.market.symbols[pair[1]],
                    memory_mean=float(memory),
                    matured_count=int(self.matured_count),
                )
            return self.parent.decide(observation)
        return self._call_blocking_ordinary_displacement(observation, pair)

    def identity(self):
        root = Path(__file__).parent
        return {
            "name": "offensive_matured_displacement_memory",
            "parameters": asdict(self.parameters),
            "implementation_sha256": file_hash(Path(__file__)),
            "contract_sha256": file_hash(root / "offensive_matured_displacement_memory_contract.json"),
            "fresh_parent_sha256": file_hash(root / "offensive_fresh_challenger_authority.py"),
            "control_sha256": file_hash(root / "offensive_campaign_peak_authority.py"),
            "data_sha256": self.market.fingerprint(),
            "horizon": self.horizon,
            "status": "RESEARCH_NOT_ACCEPTED",
        }


__all__ = ["Owner", "Parameters", "grid", "preserve_trace", "verify_trace"]
